### ISSUE TITLE
Develop Search feature

### ISSUE THREAD

**Issue by dellisd** [Llamabagel/transpo-android#14]
Create a Search Activity that can be overlaid on top of any content in the app that allows the user to search for content.

Ordinarily, this content will be stops, or routes, but could be extended to include searches for "places" and other content.

**Comment by GustavoSanMartin** [comment]
This is a huge issue. Should be broken up into smaller issues

**Comment by GustavoSanMartin** [comment]
This is a huge issue and should be broken up into smaller issues

**Comment by dellisd** [comment]
Good idea
